### ISSUE TITLE
Please provide the documentation how to use this on azure

### ISSUE THREAD

**Issue by ynagarjuna1995** [masonkmeyer/loopback-azure-test#1]
How to install strongloop's loopback on azure and how to use this repository

Thanks in advance

**Comment by masonkmeyer** [comment]
@ynagarjuna1995 Sorry, for the delayed response but I never did get this working correctly on an Azure website. I made this repo to try a super simple site (because my actual loopback app is much more complicated). If you have any luck deploying it on an Azure website let me know, I may come back to it but I had to abandon my efforts for now.
